#!/bin/sh
#
# Usage: main
# Description: checkout the main branch and delete all other branches locally

main() {
  local main_branch=$(git_main_branch)

  git checkout $main_branch && git branch | grep -v $main_branch | xargs git branch -D
}
