alias tf='terraform'
alias tfc='terraform console'
alias tff='terraform fmt -recursive .'
alias tfi='terraform init'
alias tfiu='terraform init -backend=false -upgrade'
alias tft='terraform test'
alias tfv='terraform validate'
